name: 'Build Rust Binary'
description: 'Builds cscan-server binary for a specific target platform'

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true
  os:
    description: 'Operating system (ubuntu-latest, macos-latest, windows-latest)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}

    - name: Install cross-compilation tools (Linux ARM64)
      if: inputs.target == 'aarch64-unknown-linux-gnu'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Configure linker for ARM64
      if: inputs.target == 'aarch64-unknown-linux-gnu'
      shell: bash
      run: |
        mkdir -p .cargo
        cat > .cargo/config.toml << EOF
        [target.aarch64-unknown-linux-gnu]
        linker = "aarch64-linux-gnu-gcc"
        EOF

    - name: Build binary
      shell: bash
      working-directory: packages/cscan-core
      run: cargo build --release --target ${{ inputs.target }}

    - name: Prepare binary
      shell: bash
      run: |
        cd packages/cscan-core/target/${{ inputs.target }}/release
        if [[ "${{ inputs.os }}" == "windows-latest" ]]; then
          cp cscan-server.exe cscan-server-${{ inputs.target }}.exe
          echo "BINARY_NAME=cscan-server-${{ inputs.target }}.exe" >> $GITHUB_ENV
        else
          cp cscan-server cscan-server-${{ inputs.target }}
          echo "BINARY_NAME=cscan-server-${{ inputs.target }}" >> $GITHUB_ENV
        fi

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ inputs.target }}
        path: packages/cscan-core/target/${{ inputs.target }}/release/${{ env.BINARY_NAME }}
